# Generated by Django 2.2.4 on 2019-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0003_auto_20190905_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
