# Generated by Django 2.2.4 on 2019-09-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_remove_message_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
