# Generated by Django 2.2.4 on 2019-08-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_url',
            field=models.URLField(blank=True),
        ),
    ]
